# Generated by Django 4.2.6 on 2023-10-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_product_sort_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_rus',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
