# Generated by Django 4.2.6 on 2023-10-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_product_sort_rus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mera_price',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
