# Generated by Django 5.0.1 on 2024-01-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0014_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
    ]
