# Generated by Django 5.0.1 on 2024-02-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0016_category_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mera_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sort_rus',
        ),
    ]
