# Generated by Django 5.0.1 on 2024-02-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0019_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
