# Generated by Django 5.0.1 on 2024-02-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0024_alter_category_store_alter_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
