# Generated by Django 5.0.1 on 2024-02-08 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0027_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_store', to='myshop.store'),
        ),
    ]
