# Generated by Django 5.0.1 on 2024-02-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0028_gallery_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
